# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115e5a6ef5ca24ec7683d729f5e27fa01a18624aa8fd442d945d39304c813ad949a16676a14c7e47b4321465d2ea224767a250d22c94a1d3bc796c79113c40eb

test:
  secret_key_base: 54fac1a22f35dde5f9bb7caf14083cb8be38710b4ecb36acf545dee2083581e2cf944ccccbb69eabddacb1efd0edf604000f001cac979a40438fb23d8df0f422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
